version: '3'

services:
  metacubexd:
    container_name: metacubexd
    image: ghcr.io/metacubex/metacubexd
    restart: always

  meta:
    container_name: meta
    image: docker.io/metacubex/mihomo:Alpha
    restart: always
    volumes:
      - ./config.yaml:/root/.config/mihomo/config.yaml